-- Run this in Supabase SQL Editor.
create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  family_id text not null,
  family_name text not null,
  guest_name text not null,
  response text not null check (response in ('yes','no')),
  submitted_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (family_id, guest_name)
);

alter table public.rsvps enable row level security;

-- Public guests may submit/update only through the RSVP page.
-- For a simple private event, the public anon key can be allowed to upsert.
-- The admin dashboard should NOT be publicly linked.
drop policy if exists "public can submit rsvps" on public.rsvps;
create policy "public can submit rsvps"
on public.rsvps for insert
to anon, authenticated
with check (response in ('yes','no'));

drop policy if exists "public can update rsvps" on public.rsvps;
create policy "public can update rsvps"
on public.rsvps for update
to anon, authenticated
using (true)
with check (response in ('yes','no'));

-- Host dashboard reads should be protected in production.
-- For the first build, add a Supabase Auth login before publishing admin.html.
